### ISSUE TITLE
Inconsistent behavior with Save Link/Image As between Chromium/Firefox

### ISSUE THREAD

**Issue by Baddest-Juju** [ugetdm/uget-extension#1] opened 2018-02-13 22:48 UTC
Consistency is good, right? Here's the problem.

In Chromium, __all__ downloads are intercepted, regardless of method. So if you do 'save link as', it's going to go through the uget_integrator. Also, clicking on something that would normally embed within the browser, like a pdf or mp3, will also initiate a download. I like this behavior, personally, the whitelist/blacklist can always be adjusted to compensate for this.

In Firefox however, while the things that normally embed will download if clicked on normally, any link that you use the 'save link/image as' context option will always download through the browser regardless of your extension rules.

**Comment by slgobinath** [comment] 2018-02-13 23:57
Hi,
Could you please share the link you used for testing?

**Comment by Baddest-Juju** [comment] 2018-02-14 00:04
Uh, link? Just reduce the threshold for download interrupts to 1 and try using Save Link/Image As on any website ever. Like, I personally did saving the banners on duckduckgo and google and a github icon, right click save as on a raw link on github...

but here, if you need something, try Right click > Save Link As on the big green 'Download For Windows' button on both browsers on this site: https://www.whatsapp.com/download/

**Comment by slgobinath** [comment] 2018-02-14 00:11
I use Notepad++ download link for my testings. Using that I couldn't reproduce it.
https://notepad-plus-plus.org/repository/7.x/7.5.4/npp.7.5.4.Installer.exe

I tried https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe too but uGet catches the download. I will try on different links and test this behavior

**Comment by Baddest-Juju** [comment] 2018-02-14 00:16
To be clear, you are doing a right click and then then pressing 'save link as', right? You're not just clicking on it? In Firefox Quantum?

**Comment by slgobinath** [comment] 2018-02-14 00:20
Yeah.
Once I select `Save Link As...`, Firefox asks me to select the download location. I click the save button then uGet New Download dialog appears.

Firefox Version: 58.0.2 (64-bit)
OS: Linux Mint 18.3

FYI: A bug related to Youtube download option is fixed just now in https://github.com/ugetdm/uget-extension/commit/b7a9da573f681596bd4989644b5d5bc0c81b51eb

**Comment by Baddest-Juju** [comment] 2018-02-14 00:22
Huh... you're right. I think I know what's happening here.

When you click it on chrome, before you even choose where to save it, it's already downloading in the background.

But in Firefox, it doesn't start downloading until you pick the location and hit save, so there's nothing to catch.

I wonder if there's an about:config setting for this...

**Comment by slgobinath** [comment] 2018-02-14 00:26
Try saving the file and see whether it is interrupted.
In `about:preferences` there is a category named **Applications**. There you can pick `Save File` or `Always Ask`
I think this what you are looking for.

**Comment by Baddest-Juju** [comment] 2018-02-14 00:32
There are instances where you need to right click something and do 'Save As' rather than just clicking it.

Basically, the download dialog that comes up for firefox is meaningless, because the download hasn't actually started yet. As soon as you hit save, it's caught by uGet.

That's just kinda dumb, it annoys me. I don't think there's any way to override this behavior, but I'm still looking. I looked in Applications and didn't see any helpful there.

**Comment by Baddest-Juju** [comment] 2018-02-14 00:34
Interestingly, if you have 'Always ask where to save files' selected and you click on a downloadable item, it's still caught without the Save As dialog coming up.

It's only when you do the context menu Save As it's not caught right away, there'll be a step where it wants you to save it somewhere but it doesn't actually matter where you choose.

**Comment by Baddest-Juju** [comment] 2018-02-14 00:37
Doesn't seem like it can catch browser.altClickSave (when set to true) right away either...

**Comment by slgobinath** [comment] 2018-02-14 00:43
I am closing this issue because this is something related to Firefox.
In my Firefox, I set GZ files to Always Download. So they are interrupted without showing a Save dialog. exe files show the Save dialog and I don't find an option for exe there.

@DanaMW shared something related to this problem here: https://github.com/ugetdm/uget-integrator/issues/3

Another workaround is right click on link and select `Download with uGet`.

**Closed** 2018-02-14 00:43 UTC

**Comment by Baddest-Juju** [comment] 2018-02-14 01:47
Hell, I've been looking for a workaround to make the Save As work for an hour and half and there doesn't seem to be one. Seems Download with uGet is the only option if you want to right-click download. Oh well..
